### ISSUE TITLE
Automatic port detection

### ISSUE THREAD

**Issue by oyi77** [pentagridsec/smsgate#3]
I have an idea, if we could scan all the port in pc to find the possible modem port, and test all of it, then add it to the config automatically. After the first initialization, if there are any port changes, it could update the data automatically based on the imei, and auto disabling the port if imei doesn't found on second scan attempt. 

And maybe this is as all of us want, complete API documentation, for this tool.

Below is my example snippet, for scanning possibly modem port, maybe it could help :
````
def find_all_port():
    all_port_tuples = list(list_ports.comports())
    all_ports = []
    for port in all_port_tuples:
        if port.device.startswith("COM") or port.device.startswith("ttyACM") or "ttyUSB" in port.device:
                all_ports.append({"portLoc": port.device, "status": ""})
    if len(all_ports) == 0:
        logging.error("No valid port detected!. Possibly, device not plugged/detected.")
        pass
    return all_ports
```

**Comment by nitram2342** [comment]
Thanks for thinking about this topic. It makes sense to implement this in the SerialPortMapper class and to write a "hint" file to speed up a restart. May I ask you how many modem slots do you operate and how often do you restart the service?

**Comment by oyi77** [comment]
modem slots i operate is around 256 - 1024 modem, so it could be a big help, to whoever use this module as their base library for handling sms gateway or something like that. 

for the restart i actually restart it for every 15 minutes. but for the convenience, it could be achieved by start checking or just sending basic command to check if there is something change in the modem port, and then update its recent value to the database, or the config file.

That's the usage i can think of, you could add other enhancement for this very basic idea of mine.

**Comment by nitram2342** [comment]
I very appreciate your response. We only have 16 modem slots, which is a much simpler setup then. I just implemented this feature. Please check the `Readme.txt` and config file examples for `/var/cache/smsgate/serial_ports.hints`.

Is there a need to restart the service? Do you experience many lost modems? What kind of hardware do you use?

**Comment by oyi77** [comment]
Hi, sorry for late reply, i just happen to check github again.
So the modempool i use is the same as your 16 modem slots. But i cascade it, so one usb port can be used as 4 modem pools.
And the total is 16*4 = 64 modem slots/usb.

the need to restart modem is, if there is in case : 
- bug
- lost signal
- ussd cant be send

the restart can be configured is good.

my hardware was mixed :
- Foxcomm
- Wavecom
- Qualcomm

**Comment by nitram2342** [comment]
Modem pools often have s switch per modem. It should work, when individual slots are powered off and started, again. For USSD I noticed that some providers don't like to get USSD requests to frequently. Therefore, for my config I request balance only once per hour. But I know, what you mean. I also have two SIM cards, where the modem re-initializes frequently. There is an initialization counter in the statistics and it shows which modems/cards tend to have problems.

**Comment by oyi77** [comment]
okaay, got it. thank you. your work was awesome. 
and i see that you covered every usage that general. 

it would be a big help to me.
